# 使用docker-compose 3.7版本
version: "3.7"
services:
  csapp:
    tty: true
    image: ubuntu:18.04
    container_name: craft
    build: .
    volumes:
      - ./craft/:/craft/
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
